name: .NET

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'changelog.md'
    - 'license.txt'
    - 'readme.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 9
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Build
      run: dotnet build -c Debug

    - name: Install Playwright Browsers
      run: pwsh tests/VcrSharp.Integration.Tests/bin/Debug/net9.0/playwright.ps1 install --with-deps

    - name: Test (Debug)
      run: dotnet test -c Debug --no-build

    - name: Build, Tests, Cover, Pack and Publish (on push tag)
      if: startsWith(github.event.ref, 'refs/tags/')
      run: |
        dotnet build
        pwsh tests/VcrSharp.Integration.Tests/bin/Debug/net9.0/playwright.ps1 install --with-deps
        dotnet tool install --global dotnet-releaser
        dotnet-releaser run --nuget-token ${{secrets.NUGET_TOKEN}} --github-token ${{secrets.GITHUB_TOKEN}} src/VcrSharp.Cli/dotnet-releaser.toml
